name:                haskell-hello-world
version:             0.1.0.0
github:              "ArtemisMucaj/haskell-hello-world"
license:             BSD3
author:              "Artemis Mucaj"
maintainer:          "artemis.mucaj@gmail.com"
copyright:           "2018 Artemis Mucaj"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- bytestring
- wai
- warp
- http-types

library:
  source-dirs: src

executables:
  haskell-hello-world-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hello-world

tests:
  haskell-hello-world-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hello-world
